language: node_js

node_js:
  - "7"

cache:
  directories:
    "node_modules"

before_install:
  - npm install npm
  - npm install

before_script:
  - npm run build

after_success:
  - npm run test:coverage

on:
  branch: master
